package com.example.sos

// This Enum defines every possible screen in your Pip-Boy
enum class Screen {
    Dashboard,
    Sos,
    Mesh,
    Map,
    Bio,
    Rad,
    Settings,
    Compass,
    Guide,
    Morse,
    CrashCountdown,
    Barometer,
    SkyScanner,
    Forecaster,
    Ai,
    Voice,
    // --- NEW SCREENS ---
    VibrationMorse,
    AudioMorse,
    CameraMorse,
    SosTemplates,
    DeadReckoning,
    CoordShare,
    Waypoints,
    SunCalc,
    StarNav,
    SurvivalCalc,
    TtsSos,
    QRSos,
    BatterySaver,
    EmergencyContacts,
    BiometricLock,
    Checklist,
    Dogtag,
}
